### PR TITLE
Fixes to ensure answers shared to twitter post more reliably

### LINKED ISSUE #99: Write proper text shortening utilities
_Coincides with #96_

Currently, we cut texts in a lot of places, like answers if they are too long, notifications and in social media posts.

The currently used method is really ugly and causes weird problems with formatted text, or words are cut off.

**To Do:**
* Write text cutting utilities that:
  * Preserve words
  * Properly preserves links
  * Manage to handle formatted text somewhat gracefully
  * **Twitter:** Properly utilize the available character space and not estimate by random lengths.
* Write tests for those new utilities

### PR DESCRIPTION
**Pull request by raccube**
Closes #99

### CODE REVIEW

File: spec/models/services/twitter_spec.rb [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+            'consumer_key' => 'AAA',
+          }
+        }
+      })
+    end
+
+    it "posts a shortened tweet" do
+      service.post(answer)
+
+      expect(twitter_client).to have_received(:update!).with("#{'q' * 123}… — #{'a' * 124}… https://example.com/#{user.screen_name}/a/#{answer.id}")
```
Comment (nilsding) [inline spec/models/services/twitter_spec.rb:32]: please also add another one for testing unshortened texts

**Review by nilsding — CHANGES_REQUESTED** [review]

**Comment by nilsding** [comment]
`libidn-devel` is installed on the hosts, so bundling should work.

**Review by nilsding — APPROVED** [review]

**Review by pixeldesu — APPROVED** [review]
