### PR TITLE
Fix exception being thrown upon attempting to ban a user

### LINKED ISSUE #75: Banning over the frontend doesn't work anymore
Not the functionality in the backend, but the modal on user profiles appears to have lost functionality.

My first guess seems to be that the IDs `bootstrap_forms` assigns to elements has changed and with that, the CoffeeScript related to displaying data and sending the AJAX request is now broken.

### PR DESCRIPTION
**Pull request by raccube**
Fixes #75

### CODE REVIEW

**Review by nilsding — APPROVED** [review]

File: app/assets/javascripts/moderation/ban.coffee [hunk 1]
```diff
@@ -1,22 +1,27 @@
...
 
-  parent.find('#_ban').on "change", (event) ->
+  banCheckbox.addEventListener "change", (event) ->
     $t = $ this
     if $t.is(":checked")
       $("#ban-controls").show()
     else
       $("#ban-controls").hide()
-  parent.find('#_permaban').on "change", (event) ->
+  permabanCheckbox.addEventListener() "change", (event) ->
```
Comment (pixeldesu) [inline app/assets/javascripts/moderation/ban.coffee]:
```suggestion
  permabanCheckbox.addEventListener "change", (event) ->
```

Not even sure if this qualifies as a syntax error in CoffeeScript's book, but at least choose to keep it same-y. Removing the parenthesis would adjust it to the same style as all the other `addEventListener` calls you made.

**Review by pixeldesu — CHANGES_REQUESTED** [review]

**Review by pixeldesu — APPROVED** [review]
